FROM rust:1.88 AS builder

WORKDIR /app
COPY . .

RUN cargo build --release -p workers

FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update \
	&& apt-get install -y --no-install-recommends ca-certificates libssl3 \
	&& rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/workers /app/workers

CMD ["./workers"]
