FROM rust:1.75 as builder

WORKDIR /app
COPY . .

RUN cargo build --release -p workers

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/target/release/workers /app/workers

CMD ["./workers"]
