# ---------- Build stage ----------
FROM rust:1.75 as builder

WORKDIR /app

# Copy toàn bộ project
COPY . .

# Build binary
RUN cargo build --release -p api

# ---------- Runtime stage ----------
FROM debian:bookworm-slim

WORKDIR /app

# Copy binary từ builder
COPY --from=builder /app/target/release/api /app/api

# Expose port
EXPOSE 3000

# Run
CMD ["./api"]
