# ---------- Build stage ----------
FROM rust:1.88 AS builder

WORKDIR /app

# Copy toàn bộ project
COPY . .

# Build binary
RUN cargo build --release -p api

# ---------- Runtime stage ----------
FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update \
	&& apt-get install -y --no-install-recommends ca-certificates libssl3 \
	&& rm -rf /var/lib/apt/lists/*

# Copy binary từ builder
COPY --from=builder /app/target/release/api /app/api

# Expose port
EXPOSE 3000

# Run
CMD ["./api"]
